---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-test-app-latest
  namespace: acm-test-project
spec:
  type: GitHub
  pathname: https://github.com/dzungdo/rhacm-labs.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acm-test-app
  namespace: acm-test-project
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - acm-test-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acm-test-app
  namespace: acm-test-project
  labels:
    app: acm-test-app
  annotations:
    apps.open-cluster-management.io/github-path: resources/acm-test
spec:
  channel: acm-test/acm-test-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: betadev-cluster

